### ISSUE TITLE
Use minifyJS options hash

### ISSUE THREAD

**Issue by rmharrison** [ember-cli/ember-cli-uglify#20]
Do you want a PR to use the minifyJS options hash?

I think it will cause confusion if options have to be moved from the minifyJS hash to the ember-cli-uglify hash. I'd just allow the `enable`, `exclude` and `uglify` options to be set in either minifyJS or ember-cli-uglify (precedence), as I'm unaware of other minifyJS options that would need to be passed.

For on-boarding, documentation [1](https://ember-cli.com/asset-compilation) would also need to be updated if minifyJS hash is dropped.

**Comment by rwjblue** [comment]
I think supporting enabled in minifyJS and warning if we detect any other options would be fine.

**Comment by rwjblue** [comment]
In retrospect (3 years later 😞), we should have done this when you opened this issue @rmharrison. I'm sorry about that.

At this point, most folks are passing options in `ember-cli-uglify` now, so adding support for `minifyJS` would actually not be great (due to the amount of time that has elapsed). 

I tried to ensure we didn't make the same mistake during the rename to ember-cli-terser (over in #230).
